name: 'Deploy Function App'
description: 'Deploys a Function App to Azure'
inputs:
  azureServiceConnection:
    description: 'The Azure service connection to use for deploying the Function App'
    required: true
  artifactName:
    description: 'The name of the artifact to deploy'
    required: true
  environmentToDeploy:
    description: 'The environment to deploy the Function App to'
    required: true
  vars:
    description: 'An object containing various variables needed for the deployment'
    required: true
  artifactsDirectory:
    description: 'The directory where the artifacts to deploy are located'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce
      shell: bash

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      shell: bash

    - run: echo "${{ inputs.vars.DockerRegistryPassword }}" | docker login ${{ inputs.vars.ContainerRegistryName }}.azurecr.io -u ${{ inputs.vars.DockerRegistryUsername }} --password-stdin
      shell: bash

    - run: |
        docker build -t ${{ inputs.vars.ContainerRegistryName }}.azurecr.io/${{ inputs.vars.DockerImageRepository }}:${{ github.run_id }} -f ${{ inputs.vars.DockerFilePath }} .
        docker push ${{ inputs.vars.ContainerRegistryName }}.azurecr.io/${{ inputs.vars.DockerImageRepository }}:${{ github.run_id }}
      shell: bash

    - run: |
        az functionapp config appsettings set \
          --name ${{ inputs.vars.FunctionAppName }} \
          --resource-group ${{ inputs.vars.ResourceGroupName }} \
          --settings FUNCTIONS_WORKER_RUNTIME=python
        az functionapp config appsettings set \
          --name ${{ inputs.vars.FunctionAppName }} \
          --resource-group ${{ inputs.vars.ResourceGroupName }} \
          --settings BUILD_ID=${{ github.run_id }}
      shell: bash

    - run: |
        az functionapp config container set \
          --name ${{ inputs.vars.FunctionAppName }} \
          --resource-group ${{ inputs.vars.ResourceGroupName }} \
          --docker-custom-image-name ${{ inputs.vars.ContainerRegistryName }}.azurecr.io/${{ inputs.vars.DockerImageRepository }}:${{ github.run_id }} \
          --docker-registry-server-url https://${{ inputs.vars.ContainerRegistryName }}.azurecr.io
      shell: bash
